// BouyonTV player hardening: isolated Live TV playback with automatic source failover.
(() => {
  const video=document.getElementById('video'),player=document.getElementById('player'),vod=document.getElementById('vod'),frame=document.getElementById('frame'),title=document.getElementById('title'),status=document.getElementById('status');
  if(!video||!player||!vod||!frame)return;
  let hls=null,sources=[],sourceIndex=0,channels=[];
  const setStatus=(t,e=false)=>{if(status){status.textContent=t;status.className='status'+(e?' error':'')}};
  const show=()=>{document.getElementById('home')?.style&&(document.getElementById('home').style.display='none');document.getElementById('browse')?.style&&(document.getElementById('browse').style.display='none');player.classList.add('active')};
  const destroy=()=>{if(hls){try{hls.destroy()}catch{}hls=null}video.pause();video.removeAttribute('src');video.load();frame.src='';vod.style.display='none';video.style.display='block'};
  const proxy=u=>`/api/stream?url=${encodeURIComponent(u)}`;
  const next=()=>{if(sourceIndex>=sources.length){setStatus('No playable source found for this channel.',true);return}const original=sources[sourceIndex++];setStatus(`Connecting to source ${sourceIndex}/${sources.length}…`);const src=proxy(original);if(window.Hls&&Hls.isSupported()){hls=new Hls({enableWorker:true,lowLatencyMode:true,backBufferLength:15,maxBufferLength:30});hls.attachMedia(video);hls.once(Hls.Events.MEDIA_ATTACHED,()=>hls.loadSource(src));hls.once(Hls.Events.MANIFEST_PARSED,()=>video.play().then(()=>setStatus('Playing')).catch(()=>setStatus('Ready — tap play')));hls.on(Hls.Events.ERROR,(_,d)=>{if(!d.fatal)return;try{hls.destroy()}catch{}hls=null;setStatus(`Source ${sourceIndex} failed, trying next…`);setTimeout(next,100)});return}if(video.canPlayType('application/vnd.apple.mpegurl')){video.src=src;video.load();video.play().then(()=>setStatus('Playing')).catch(()=>setStatus('Ready — tap play'));video.onerror=()=>next();return}setStatus('HLS is not supported in this browser.',true)};
  const playLive=c=>{show();destroy();sources=[...(Array.isArray(c.sources)?c.sources.map(s=>typeof s==='string'?s:s?.url):[]),c.url].filter(Boolean).filter((u,i,a)=>a.indexOf(u)===i);sourceIndex=0;title.textContent=c.name||'Live TV';if(!sources.length)return setStatus('No stream URL is available.',true);next()};
  fetch('/api/catalog',{cache:'no-store'}).then(r=>r.ok?r.json():null).then(d=>{channels=d?.channels||[];window.__bouyonChannels=channels}).catch(()=>{});
  document.addEventListener('click',e=>{const card=e.target.closest('.live-card');if(!card)return;const id=card.dataset.id,c=channels.find(x=>String(x.id)===String(id)||String(x.name)===String(id));if(!c)return;e.preventDefault();e.stopImmediatePropagation();playLive(c)},true);
  window.__bouyonPlayLive=playLive;
})();